
export const REQUEST_PRODUCTS           = 'REQUEST_PRODUCTS';
export const REQUEST_PRODUCTS_SUCCESS   = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_FAIL      = 'REQUEST_PRODUCTS_FAIL';

export const REQUEST_CATEGORIES         = 'REQUEST_CATEGORIES';
export const REQUEST_CATEGORIES_SUCCESS = 'REQUEST_CATEGORIES_SUCCESS';
export const REQUEST_CATEGORIES_FAIL    = 'REQUEST_CATEGORIES_FAIL';

export const CART_ADD_PRODUCT           = 'CART_ADD_PRODUCT';
export const CART_REMOVE_PRODUCT        = 'CART_REMOVE_PRODUCT';
export const CART_INCREMENT_PRODUCT     = 'CART_INCREMENT_PRODUCT';
export const CART_DECREMENT_PRODUCT     = 'CART_DECREMENT_PRODUCT';
