
export const REQUEST_PRODUCTS           = 'REQUEST_PRODUCTS';
export const REQUEST_PRODUCTS_SUCCESS   = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_FAIL      = 'REQUEST_PRODUCTS_FAIL';

export const REQUEST_CATEGORIES         = 'REQUEST_CATEGORIES';
export const REQUEST_CATEGORIES_SUCCESS = 'REQUEST_CATEGORIES_SUCCESS';
export const REQUEST_CATEGORIES_FAIL    = 'REQUEST_CATEGORIES_FAIL';

export const CART_ADD_ITEM              = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM           = 'CART_REMOVE_ITEM';
export const CART_INCREASE_ITEM         = 'CART_INCREASE_ITEM';
export const CART_DECREASE_ITEM         = 'CART_DECREASE_ITEM';
